### ISSUE TITLE
Implement `POST /job/applications`

### ISSUE THREAD

**Issue by refigo** [refigo/wanted-pre-onboarding-backend#18]
## TODO
- [x] refactor: Applications -> JobApplications
- [x] feat: Implement `POST /job/applications`
- [x] docs: Write to update `POST /job/applications`
