### ISSUE TITLE
Clearing unused

### ISSUE THREAD

**Issue by refigo** [refigo/wanted-pre-onboarding-backend#20]
## TODO
- [x] Clear unused Methods
- [x] Clear unused Entities
- [x] Clear unused DTOs
